### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by Minecrell**

### CODE REVIEW

**Comment by Spongy** [comment]
Can one of the admins verify this patch?

**Comment by Minecrell** [comment]
ok to test

**Comment by Minecrell** [comment]
retest this please

**Comment by Minecrell** [comment]
retest this please

**Comment by Minecrell** [comment]
retest this please

**Comment by Minecrell** [comment]
retest this please

**Comment by Minecrell** [comment]
retest this please

**Comment by Minecrell** [comment]
retest this please

**Pull request closed without merging**
